apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
data:
  SERVICE_VERSION: v1
  POSTGRES_USER: postgres
  POSTGRES_DB: innocent
  POSTGRES_HOST: postgres-postgresql-ha-postgresql
