apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    {{- include "espresso-review.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.cm.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "espresso-review.selectorLabels" . | nindent 4 }}
    {{- include "espresso-review.selectorLabels-2" . | nindent 4 }}


